### ISSUE TITLE
Update renv and rsconnect

### ISSUE THREAD

**Issue by GuidoMaggio** [miraisolutions/ShinyCICD#16]
few updates have been introduced with renv >1 and rsconnect >1

https://rstudio.github.io/renv/articles/rsconnect.html

https://community.rstudio.com/t/notice-posit-cloud-dropping-support-for-rsconnect-1-0-1/172078

Update renv lock, test deployApp call, update to latest R version

See also this failed run
https://github.com/miraisolutions/ShinyCICD/actions/runs/6069971717/job/16465183361

**Comment by GuidoMaggio** [comment]
Deployment with CI-CD workflow is working with
- renv 1.0.0
- rsconnect not in the renv lock
- options(rsconnect.packrat = TRUE) in deploy script
https://github.com/miraisolutions/ShinyCICD/actions/runs/6096147442/job/16541768310

CI-CD-renv works as well, but the deploy step would require options(rsconnect.packrat = FALSE).

I believe in this case the rsconnect package should be in the renv.lock

**Comment by GuidoMaggio** [comment]
renv 1.0.0
rsconnect 0.8.29 in DESCRIPTION file

The deployment works in this case, no need to set options(rsconnect.packrat = FALSE)

options(repos=c(CRAN="https://cran.rstudio.com")) must be set

https://github.com/miraisolutions/ShinyCICD/actions/runs/6157115509/job/16707190231

With rsconnect 1.0.0 and 1.0.2 the deployment fails
https://github.com/miraisolutions/ShinyCICD/actions/runs/6156956472/job/16706687582 (1.0.0)
https://github.com/miraisolutions/ShinyCICD/actions/runs/6148343567/job/16681842818 (1.0.2)

In this issue, some problems with higher versions of rsconnect
https://community.rstudio.com/t/shinyapps-io-deploy-error-409-application-exists-with-name/170488/3

rsconnect 1.0.0 seems to have bugs that were fixed in rsconnect 1.1.0

The renv deployment works with
options(repos=c(CRAN="https://cran.rstudio.com"))
rsconnect in DESCRIPTION
writeManifest() creates the json
https://github.com/miraisolutions/ShinyCICD/actions/runs/6158133872/job/16710302504

**Comment by GuidoMaggio** [comment]
I have changed the deployment doing:

renv::init(settings = list(snapshot.type = "explicit")) # from DESCRIPTION

renv::install() in githubactions to install packages in Suggests

The deployment seems to work successfully on GitHub actions

https://github.com/miraisolutions/ShinyCICD/actions/runs/6245806391

however the app gives an error: pkgload not found (it can be seen from shinyapps.io log)

See these issues:

https://github.com/rstudio/rsconnect/issues/916 
https://stackoverflow.com/questions/76711093/missing-dependency-from-rsconnect-when-deploying-shinyapps/76715457#76715457

They mentions here that it is not possible at the moment to preserve the "explicit" dependencies without setting 

options(rsconnect.packrat = TRUE)

**Comment by GuidoMaggio** [comment]
From rsconnect documentation


### **Dependency discovery**

rsconnect use one of three mechanisms to find which packages your application uses:
1. If renv.lock is present, it will use the versions and sources defined in that file. If you’re using
the lockfile for some other purpose and don’t want it to affect deployment, add renv.lock to
.rscignore.
2. Otherwise, rsconnect will call renv::snapshot() to find all packages used by your code. If
you’d instead prefer to only use the packages declared in a DESCRIPTION file, run renv::settings$snapshot.type("explicit") to activate renv’s "explicit" mode.
3. Dependency resolution using renv is a new feature in rsconnect 1.0.0, and while we have done
our best to test it, it still might fail for your app. If this happens, please file an issue then set
options(rsconnect.packrat = TRUE) to revert to the old dependency discovery mechanism


So to get the option 2, we must add the`.rscignore` file with `renv.lock`

The snapshot from installed packages works, however it does not install ShinyCICD, which is required in the call `ShinyCICD::run_app()`

```
The following required packages are not installed:
- ShinyCICD
```

https://github.com/miraisolutions/ShinyCICD/actions/runs/6249606464/job/16966640286

It could be solved doing

```
pkgload::load_all(export_all = TRUE, helpers = FALSE,attach_testthat = FALSE)
options( "golem.app.prod" = TRUE)
run_app() 
```
adding `tests` folder to `.rscignore`, ShinyCICD where is mentioned

and

`renv::settings$snapshot.type("explicit")` to the deploy script.

This works locally but fails on GitHub Actions

https://github.com/miraisolutions/ShinyCICD/actions/runs/6250872503/job/16970686795
```
The following required packages are not installed:
- ShinyCICD
```

Still needed, I assume due to

```
app_sys <- function(...){
  system.file(..., package = "ShinyCICD")
}
```
I go back to 
`options(rsconnect.packrat = TRUE)  with explicit

https://github.com/miraisolutions/ShinyCICD/actions/runs/6250956056/job/16971084886

**Comment by riccardoporreca** [comment]
@GuidoMaggio, as of today, the ultimate issue with the rsconnect update was that it would try to bundle dependencies for the deployment using the `renv.lock` in the repo.
This could be easily fixed by ignoring it (which is something we want for both CI-CD and CI-CD-renv) , see dd8c221a79a486c7ea6fc49882547358c6e220b2
